BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "yokto"
BBFILE_PATTERN_yokto = "^${LAYERDIR}/"
BBFILE_PRIORITY_yokto = "12"
LAYERSERIES_COMPAT_yokto = "scarthgap"