BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "doom"
BBFILE_PATTERN_doom = "^${LAYERDIR}/"
BBFILE_PRIORITY_doom = "10"
LAYERSERIES_COMPAT_doom = "scarthgap"