# Yokto distribution configuration - extends poky
DISTRO = "yokto"
DISTRO_NAME = "Yokto gaming distro"

# Inherit poky base
require conf/distro/poky.conf

# Disable SPDX SBOM creation
INHERIT:remove = "create-spdx"