BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "games"
BBFILE_PATTERN_games = "^${LAYERDIR}/"
BBFILE_PRIORITY_games = "10"
LAYERSERIES_COMPAT_games = "scarthgap"