BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "quake3"
BBFILE_PATTERN_quake3 = "^${LAYERDIR}/"
BBFILE_PRIORITY_quake3 = "10"
LAYERSERIES_COMPAT_quake3 = "scarthgap"